### ISSUE TITLE
Pandoc generated README.rst should pass PyPI's strict reST check 

### ISSUE THREAD

**Issue by laike9m** [laike9m/pdir2#24]
#22

**Comment by mdraw** [comment]
Looks like the problem is that pandoc sees the 🍺  emoji as one character, whereas docutils (the reST implementation) sees it as two characters and therefore expects one underline character more.
IMHO this is not a bug in pandoc but in docutils. This issue might be related: https://sourceforge.net/p/docutils/bugs/128/ but creating a new bug for our particular issue may be a good idea.

There is another (really) small issue with the pandoc-generated Reame: The indentation in the last bullet point of the "Features" section disappears in the reST form. This may be a bug in pandoc.

How about replacing the README.md completely with README.rst? Then you'd have better control over the formatting and you wouldn't have to manually keep them in sync with pandoc.

**Comment by laike9m** [comment]
Thanks Martin, the information is very helpful. I'll look at this issue tonight when I get home.

**Comment by mdraw** [comment]
No problem, I'm glad I can help. I had very similar problems too once and was really confused until I stumbled upon this thread: https://github.com/pypa/pypi-legacy/issues/161

**Comment by laike9m** [comment]
Removed the beer emoji to resolve this issue. I hope Docutils can fix this bug some day.
